### ISSUE TITLE
CIWS not working

### ISSUE THREAD

**Issue by JanB1** [itc-addons/ITC_Land_Systems#9]
Hey guys, I'm sure I'm just too dumb and do something wrong here, but I can't seem to get the CIWS working.

Setup:
2 Praetorian 2 Mod 0 on Altis Airfield, 1 Sholef on AAC Airfield, Distance 5'600m
I set the CIWS to "ON" and tried multiple shots, but the two Praetorians didn't even react. Placed an enemy vehicle in front of them just to test, and they destroyed it right away.

What am I doing wrong...

**Comment by toadball** [comment]
Could do with amplifying information.
If both the firing unit and praetorian are of the same side then the the praetorian will not engage the incoming/outgoing projectiles. That is working as intended.
If the shells are fired by a unit of a different side the CIWS should engage as expected.

As an aside:
It is worth noting that howitzer shells are very difficult to engage simply due to their particularly high velocity. We do also recommend pairing any CIWS system with a radar vehicle that works with the vanilla data link system where possible to allow for faster spotting.

**Comment by JanB1** [comment]
Aaaah, FFS!
I knew it was just me being too dumb. Gdamn it.

Ok, I tested another CIWS-Mod some time ago and it was just like "Shell? `Exterminate!`" and didn't care if the shell was friendly or not. But yeah, makes sense.

Ok, will test again. Thank you!
